apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xapp-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xapp-operator-role
subjects:
- kind: ServiceAccount
  name: xapp-operator-service-account
